from videoforge_contracts.artifact import Artifact, MediaProbe, ProducedBy, StorageRef
from videoforge_contracts.asset_plan import (
    AssetLicense,
    AssetPlan,
    AssetPlanSlot,
    CompositionSpec,
    ResolvedAsset,
)
from videoforge_contracts.base import CONTRACT_SCHEMA_VERSION, ContractModel
from videoforge_contracts.blueprint import (
    Claim,
    EvidenceSpan,
    RhetoricalBeat,
    VideoBlueprint,
    VisualBeat,
)
from videoforge_contracts.brief import (
    BriefHook,
    ClaimTable,
    ClaimTableEntry,
    CreativeBrief,
    CreativeOpportunity,
    VisualMix,
)
from videoforge_contracts.enums import (
    AssetLicenseType,
    AssetRole,
    AssetSource,
    ClaimSourceStatus,
    ContinuityRuleKind,
    CreationMode,
    EditOpKind,
    ExecutionPolicy,
    FrameSampleReason,
    HealthState,
    HighlightLabel,
    HighlightReason,
    IsolationLevel,
    ProjectStatus,
    ProviderType,
    ReframeFollow,
    RemotionComposition,
    RenderStage,
    RenderTargetKind,
    RhetoricalBeatKind,
    StorageBackend,
    TextTrackKind,
    TrackKind,
    TrendStage,
    VisualBeatKind,
)
from videoforge_contracts.highlight import (
    HighlightCandidate,
    HighlightFeatures,
    HighlightSet,
    HighlightWeights,
)
from videoforge_contracts.problem import ProblemDetail
from videoforge_contracts.project import Project
from videoforge_contracts.provider import CostModel, ProviderDescriptor, ProviderHealth
from videoforge_contracts.reedit import (
    ContinuityNote,
    EditOp,
    ReeditPlan,
    ReframeHint,
    SegmentJudgment,
)
from videoforge_contracts.remotion import (
    RemotionProp,
    RemotionRenderManifest,
    RemotionRenderRequest,
)
from videoforge_contracts.render import (
    FfmpegRenderGraph,
    FilterGraph,
    FilterNode,
    RenderInput,
    RenderManifest,
)
from videoforge_contracts.rewrite import (
    BeatSlot,
    BeatTemplate,
    ScriptSentence,
    ScriptVersion,
)
from videoforge_contracts.task_envelope import ResourceLimits, TaskEnvelope
from videoforge_contracts.texttrack import (
    BBox,
    TextObservation,
    TextTrack,
    TextTrackSet,
)
from videoforge_contracts.timeline import (
    CreativeTimeline,
    LocalizationPolicy,
    RationalTime,
    RationalTimeRange,
    Segment,
    SegmentEffect,
    Track,
)
from videoforge_contracts.transcript import (
    Transcript,
    TranscriptModels,
    TranscriptSegment,
    TranscriptWord,
)
from videoforge_contracts.trend import (
    HotScoreWeights,
    TrendCluster,
    TrendItemSnapshot,
    TrendSubScores,
)
from videoforge_contracts.vlm import FrameAnalysis, VisualAnalysis

# schemas/<name>.schema.json 与顶层合同的对应表（导出与漂移检查共用）
CONTRACTS: dict[str, type[ContractModel]] = {
    "project": Project,
    "artifact": Artifact,
    "task-envelope": TaskEnvelope,
    "provider-descriptor": ProviderDescriptor,
    "problem-detail": ProblemDetail,
    "trend-item-snapshot": TrendItemSnapshot,
    "trend-cluster": TrendCluster,
    "transcript": Transcript,
    "text-track-set": TextTrackSet,
    "visual-analysis": VisualAnalysis,
    "video-blueprint": VideoBlueprint,
    "creative-opportunity": CreativeOpportunity,
    "creative-brief": CreativeBrief,
    "claim-table": ClaimTable,
    "beat-template": BeatTemplate,
    "script-version": ScriptVersion,
    "highlight-set": HighlightSet,
    "reedit-plan": ReeditPlan,
    "asset-plan": AssetPlan,
    "creative-timeline": CreativeTimeline,
    "render-manifest": RenderManifest,
    "remotion-render-manifest": RemotionRenderManifest,
}

__all__ = [
    "CONTRACT_SCHEMA_VERSION",
    "CONTRACTS",
    "Artifact",
    "AssetLicense",
    "AssetLicenseType",
    "AssetPlan",
    "AssetPlanSlot",
    "AssetRole",
    "AssetSource",
    "BBox",
    "BeatSlot",
    "BeatTemplate",
    "BriefHook",
    "Claim",
    "ClaimSourceStatus",
    "ClaimTable",
    "ClaimTableEntry",
    "CompositionSpec",
    "ContinuityNote",
    "ContinuityRuleKind",
    "ContractModel",
    "CostModel",
    "CreationMode",
    "CreativeBrief",
    "CreativeTimeline",
    "CreativeOpportunity",
    "EditOp",
    "EditOpKind",
    "EvidenceSpan",
    "ExecutionPolicy",
    "FfmpegRenderGraph",
    "FilterGraph",
    "FilterNode",
    "FrameAnalysis",
    "FrameSampleReason",
    "HealthState",
    "HighlightCandidate",
    "HighlightFeatures",
    "HighlightLabel",
    "HighlightReason",
    "HighlightSet",
    "HighlightWeights",
    "HotScoreWeights",
    "IsolationLevel",
    "LocalizationPolicy",
    "MediaProbe",
    "ProblemDetail",
    "ProducedBy",
    "Project",
    "ProjectStatus",
    "ProviderDescriptor",
    "ProviderHealth",
    "ProviderType",
    "RationalTime",
    "RationalTimeRange",
    "ReeditPlan",
    "ReframeFollow",
    "ReframeHint",
    "RemotionComposition",
    "RemotionProp",
    "RemotionRenderManifest",
    "RemotionRenderRequest",
    "RenderInput",
    "RenderManifest",
    "RenderStage",
    "RenderTargetKind",
    "ResolvedAsset",
    "ResourceLimits",
    "RhetoricalBeat",
    "RhetoricalBeatKind",
    "ScriptSentence",
    "ScriptVersion",
    "Segment",
    "SegmentEffect",
    "SegmentJudgment",
    "StorageBackend",
    "StorageRef",
    "TaskEnvelope",
    "TextObservation",
    "TextTrack",
    "TextTrackKind",
    "TextTrackSet",
    "Track",
    "TrackKind",
    "Transcript",
    "TranscriptModels",
    "TranscriptSegment",
    "TranscriptWord",
    "TrendCluster",
    "TrendItemSnapshot",
    "TrendStage",
    "TrendSubScores",
    "VideoBlueprint",
    "VisualAnalysis",
    "VisualBeat",
    "VisualBeatKind",
    "VisualMix",
]
