from videoforge_contracts.artifact import Artifact, MediaProbe, ProducedBy, StorageRef
from videoforge_contracts.asset_plan import (
    AssetLicense,
    AssetPlan,
    AssetPlanSlot,
    CompositionSpec,
    ResolvedAsset,
)
from videoforge_contracts.audio_mix import (
    AudioMixPlan,
    AudioMixTrack,
    AudioMixTrackKind,
    DuckingPolicy,
    DuckingSidechain,
    LoudnessTarget,
)
from videoforge_contracts.base import CONTRACT_SCHEMA_VERSION, ContractModel
from videoforge_contracts.blueprint import (
    Claim,
    EvidenceSpan,
    RhetoricalBeat,
    VideoBlueprint,
    VisualBeat,
)
from videoforge_contracts.brief import (
    BriefHook,
    ClaimTable,
    ClaimTableEntry,
    CreativeBrief,
    CreativeOpportunity,
    VisualMix,
)
from videoforge_contracts.duration_fit import (
    DurationFitDecision,
    DurationFitPlan,
    DurationFitStatus,
    DurationFitStrategy,
)
from videoforge_contracts.enums import (
    AssetLicenseType,
    AssetRole,
    AssetSource,
    ClaimSourceStatus,
    ContinuityRuleKind,
    CreationMode,
    EditOpKind,
    ExecutionPolicy,
    ExporterKind,
    ExporterStatus,
    FrameSampleReason,
    HealthState,
    HighlightLabel,
    HighlightReason,
    IsolationLevel,
    ProjectStatus,
    ProviderType,
    QAFindingKind,
    QASeverity,
    ReframeFollow,
    RemotionComposition,
    RenderStage,
    RenderTargetKind,
    RhetoricalBeatKind,
    StorageBackend,
    TextTrackKind,
    TrackKind,
    TrendStage,
    VisualBeatKind,
)
from videoforge_contracts.exporter import ExportEntry, ExporterReport
from videoforge_contracts.highlight import (
    HighlightCandidate,
    HighlightFeatures,
    HighlightSet,
    HighlightWeights,
)
from videoforge_contracts.lipsync import (
    LipSyncEligibilityCriteria,
    LipSyncIneligibleReason,
    LipSyncMethod,
    LipSyncMode,
    LipSyncPlan,
    LipSyncQAReport,
    LipSyncReviewReason,
    LipSyncSegmentDecision,
)
from videoforge_contracts.localization import (
    CanonicalScript,
    CanonicalSentence,
    ClaimDelta,
    ClaimDiff,
    Glossary,
    GlossaryEntry,
    LocalizationVariant,
    LocalizedSentence,
    TranslateReflectAdaptResult,
)
from videoforge_contracts.localization_review import (
    LocalizationQACheck,
    LocalizationQAFinding,
    LocalizationQAReport,
    LocalizationReview,
    ReRunStage,
    ReviewState,
    SentenceReviewDecision,
)
from videoforge_contracts.onscreen_text import (
    CleanPlateMethod,
    CleanPlateRequest,
    TextLocalizationKindPolicy,
    TextLocalizationPlan,
    TextLocalizationPolicy,
    TextLocalizationReviewReason,
    TextLocalizationStrategy,
    TextTrackLocalizationDecision,
)
from videoforge_contracts.problem import ProblemDetail
from videoforge_contracts.project import Project
from videoforge_contracts.provider import CostModel, ProviderDescriptor, ProviderHealth
from videoforge_contracts.publish_preflight import (
    AccountStatus,
    AuthStatus,
    ClientReviewStatus,
    PlatformPublishSpec,
    PreflightCheck,
    PreflightFinding,
    PreflightReport,
    PublishConnectorCapability,
    PublishMediaProbe,
    PublishMetadata,
    PublishMethod,
    PublishPlatform,
)
from videoforge_contracts.qa import QAFinding, QAReport
from videoforge_contracts.reedit import (
    ContinuityNote,
    EditOp,
    ReeditPlan,
    ReframeHint,
    SegmentJudgment,
)
from videoforge_contracts.remotion import (
    RemotionProp,
    RemotionRenderManifest,
    RemotionRenderRequest,
)
from videoforge_contracts.render import (
    FfmpegRenderGraph,
    FilterGraph,
    FilterNode,
    RenderInput,
    RenderManifest,
)
from videoforge_contracts.review_policy import (
    ReviewDecision,
    ReviewDecisionKind,
    ReviewPolicy,
    ReviewPolicyMode,
    ReviewScope,
    ReviewSeverity,
    TemplateTrustCriteria,
    TemplateTrustLevel,
    TemplateTrustState,
    TemplateTrustStats,
)
from videoforge_contracts.rewrite import (
    BeatSlot,
    BeatTemplate,
    ScriptSentence,
    ScriptVersion,
)
from videoforge_contracts.subtitle import (
    SafeAreaSpec,
    SubtitleCue,
    SubtitleFormat,
    SubtitleLine,
    SubtitleStyleHint,
    SubtitleTemplate,
    SubtitleTrack,
    SubtitleWord,
)
from videoforge_contracts.task_envelope import ResourceLimits, TaskEnvelope
from videoforge_contracts.texttrack import (
    BBox,
    TextObservation,
    TextTrack,
    TextTrackSet,
)
from videoforge_contracts.timeline import (
    CreativeTimeline,
    LocalizationPolicy,
    RationalTime,
    RationalTimeRange,
    Segment,
    SegmentEffect,
    Track,
)
from videoforge_contracts.transcript import (
    Transcript,
    TranscriptModels,
    TranscriptSegment,
    TranscriptWord,
)
from videoforge_contracts.trend import (
    HotScoreWeights,
    TrendCluster,
    TrendItemSnapshot,
    TrendSubScores,
)
from videoforge_contracts.tts import (
    PronunciationEntry,
    PronunciationLexicon,
    TTSManifest,
    TTSProviderTier,
    TTSWordTiming,
    VoiceKind,
    VoiceLicenseStatus,
    VoiceProfile,
    VoiceStyle,
)
from videoforge_contracts.vlm import FrameAnalysis, VisualAnalysis

# schemas/<name>.schema.json 与顶层合同的对应表（导出与漂移检查共用）
CONTRACTS: dict[str, type[ContractModel]] = {
    "project": Project,
    "artifact": Artifact,
    "task-envelope": TaskEnvelope,
    "provider-descriptor": ProviderDescriptor,
    "problem-detail": ProblemDetail,
    "trend-item-snapshot": TrendItemSnapshot,
    "trend-cluster": TrendCluster,
    "transcript": Transcript,
    "text-track-set": TextTrackSet,
    "visual-analysis": VisualAnalysis,
    "video-blueprint": VideoBlueprint,
    "creative-opportunity": CreativeOpportunity,
    "creative-brief": CreativeBrief,
    "claim-table": ClaimTable,
    "beat-template": BeatTemplate,
    "script-version": ScriptVersion,
    "highlight-set": HighlightSet,
    "canonical-script": CanonicalScript,
    "glossary": Glossary,
    "translate-reflect-adapt-result": TranslateReflectAdaptResult,
    "localization-variant": LocalizationVariant,
    "reedit-plan": ReeditPlan,
    "subtitle-template": SubtitleTemplate,
    "subtitle-track": SubtitleTrack,
    "text-localization-plan": TextLocalizationPlan,
    "voice-profile": VoiceProfile,
    "pronunciation-lexicon": PronunciationLexicon,
    "tts-manifest": TTSManifest,
    "duration-fit-plan": DurationFitPlan,
    "audio-mix-plan": AudioMixPlan,
    "lipsync-plan": LipSyncPlan,
    "localization-qa-report": LocalizationQAReport,
    "localization-review": LocalizationReview,
    "review-decision": ReviewDecision,
    "review-policy": ReviewPolicy,
    "template-trust-state": TemplateTrustState,
    "platform-publish-spec": PlatformPublishSpec,
    "publish-connector-capability": PublishConnectorCapability,
    "preflight-report": PreflightReport,
    "asset-plan": AssetPlan,
    "creative-timeline": CreativeTimeline,
    "render-manifest": RenderManifest,
    "remotion-render-manifest": RemotionRenderManifest,
    "qa-report": QAReport,
    "exporter-report": ExporterReport,
}

__all__ = [
    "CONTRACT_SCHEMA_VERSION",
    "CONTRACTS",
    "Artifact",
    "AssetLicense",
    "AssetLicenseType",
    "AssetPlan",
    "AssetPlanSlot",
    "AssetRole",
    "AssetSource",
    "BBox",
    "BeatSlot",
    "BeatTemplate",
    "BriefHook",
    "Claim",
    "ClaimSourceStatus",
    "ClaimTable",
    "ClaimTableEntry",
    "CompositionSpec",
    "ContinuityNote",
    "ContinuityRuleKind",
    "ContractModel",
    "CostModel",
    "CreationMode",
    "CreativeBrief",
    "CreativeTimeline",
    "CreativeOpportunity",
    "EditOp",
    "EditOpKind",
    "EvidenceSpan",
    "ExecutionPolicy",
    "ExportEntry",
    "ExporterKind",
    "ExporterReport",
    "ExporterStatus",
    "FfmpegRenderGraph",
    "FilterGraph",
    "FilterNode",
    "FrameAnalysis",
    "FrameSampleReason",
    "HealthState",
    "HighlightCandidate",
    "HighlightFeatures",
    "HighlightLabel",
    "HighlightReason",
    "HighlightSet",
    "HighlightWeights",
    "HotScoreWeights",
    "IsolationLevel",
    "CanonicalScript",
    "CanonicalSentence",
    "ClaimDelta",
    "ClaimDiff",
    "Glossary",
    "GlossaryEntry",
    "LocalizationPolicy",
    "LocalizationVariant",
    "LocalizedSentence",
    "MediaProbe",
    "ProblemDetail",
    "ProducedBy",
    "Project",
    "ProjectStatus",
    "ProviderDescriptor",
    "ProviderHealth",
    "ProviderType",
    "QAFinding",
    "QAFindingKind",
    "QAReport",
    "QASeverity",
    "RationalTime",
    "RationalTimeRange",
    "ReeditPlan",
    "ReframeFollow",
    "ReframeHint",
    "RemotionComposition",
    "RemotionProp",
    "RemotionRenderManifest",
    "RemotionRenderRequest",
    "RenderInput",
    "RenderManifest",
    "RenderStage",
    "RenderTargetKind",
    "ResolvedAsset",
    "ResourceLimits",
    "RhetoricalBeat",
    "RhetoricalBeatKind",
    "SafeAreaSpec",
    "ScriptSentence",
    "ScriptVersion",
    "Segment",
    "SubtitleCue",
    "SubtitleFormat",
    "SubtitleLine",
    "SubtitleStyleHint",
    "SubtitleTemplate",
    "SubtitleTrack",
    "SubtitleWord",
    "CleanPlateMethod",
    "CleanPlateRequest",
    "TextLocalizationKindPolicy",
    "TextLocalizationPlan",
    "TextLocalizationPolicy",
    "TextLocalizationReviewReason",
    "TextLocalizationStrategy",
    "TextTrackLocalizationDecision",
    "PronunciationEntry",
    "PronunciationLexicon",
    "TTSManifest",
    "TTSProviderTier",
    "TTSWordTiming",
    "VoiceKind",
    "VoiceLicenseStatus",
    "VoiceProfile",
    "VoiceStyle",
    "DurationFitDecision",
    "DurationFitPlan",
    "DurationFitStatus",
    "DurationFitStrategy",
    "AudioMixPlan",
    "AudioMixTrack",
    "AudioMixTrackKind",
    "DuckingPolicy",
    "DuckingSidechain",
    "LoudnessTarget",
    "LipSyncEligibilityCriteria",
    "LipSyncIneligibleReason",
    "LipSyncMethod",
    "LipSyncMode",
    "LipSyncPlan",
    "LipSyncQAReport",
    "LipSyncReviewReason",
    "LipSyncSegmentDecision",
    "LocalizationQACheck",
    "LocalizationQAFinding",
    "LocalizationQAReport",
    "LocalizationReview",
    "ReRunStage",
    "ReviewState",
    "SentenceReviewDecision",
    "ReviewDecision",
    "ReviewDecisionKind",
    "ReviewPolicy",
    "ReviewPolicyMode",
    "ReviewScope",
    "ReviewSeverity",
    "TemplateTrustCriteria",
    "TemplateTrustLevel",
    "TemplateTrustState",
    "TemplateTrustStats",
    "AccountStatus",
    "AuthStatus",
    "ClientReviewStatus",
    "PlatformPublishSpec",
    "PreflightCheck",
    "PreflightFinding",
    "PreflightReport",
    "PublishConnectorCapability",
    "PublishMediaProbe",
    "PublishMetadata",
    "PublishMethod",
    "PublishPlatform",
    "SegmentEffect",
    "SegmentJudgment",
    "StorageBackend",
    "StorageRef",
    "TaskEnvelope",
    "TextObservation",
    "TextTrack",
    "TextTrackKind",
    "TextTrackSet",
    "Track",
    "TrackKind",
    "Transcript",
    "TranscriptModels",
    "TranscriptSegment",
    "TranscriptWord",
    "TranslateReflectAdaptResult",
    "TrendCluster",
    "TrendItemSnapshot",
    "TrendStage",
    "TrendSubScores",
    "VideoBlueprint",
    "VisualAnalysis",
    "VisualBeat",
    "VisualBeatKind",
    "VisualMix",
]
